### ISSUE TITLE
Scroll Position Forgotten in Safari After Page Reload

### ISSUE THREAD

**Issue by neildaniels** [primer/doctocat#104]
**Describe the bug**
If you scroll down on the content side of a page (such as https://primer.style/css/components/avatars) then reload the page, Safari will forget the scroll position and just go back to the top of the page.

Chrome keeps the scroll position, as expected.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 13.0.1 (15608.2.11.1.8)

**Comment by yaili** [comment]
This seem fixed now. Closing for now.
