### ISSUE TITLE
[Component] Alert

### ISSUE THREAD

**Issue by yaili** [primer/doctocat#110]
How can we draw attention to specific content? Currently, in most instances we have bold text before the paragraph:

<img width="664" alt="Screenshot 2020-01-28 at 14 26 33" src="https://user-images.githubusercontent.com/223966/73272395-353baa00-41da-11ea-97c1-c77348df95ea.png">

Used keywords: Note (4x), Attention (4x), Usage warning, Important

Could we reuse the styles from existing [alerts](https://primer.style/css/components/alerts) or [toasts](https://primer.style/css/components/toasts)? Also: [box](https://primer.style/css/components/box).

**Comment by yaili** [comment]
To keep things simple, the best solution is probably to use the existing alert style. Thoughts?

[🎨 Figma WIP](https://www.figma.com/file/qsKUZDH4xE8h6e7p7GBE8e/Doctocat-Extra-components?node-id=39%3A0)

cc @ashygee @broccolini @emplums

**Comment by colebemis** [comment]
Over the summer, we had played around with the idea of a note/alert component similar to this:

![image](https://user-images.githubusercontent.com/4608155/73797847-f53e6f00-4765-11ea-85a3-6263622f5370.png)
https://theme-ui.com/getting-started

**Comment by colebemis** [comment]
We also discussed having different colors to represent different types of "alerts." For example, blue for information, yellow for warning, pink for protip, etc.

**Comment by yaili** [comment]
I guess the [alerts](https://primer.style/css/components/alerts#variations) works the same way, except pink is for errors.

**Comment by emplums** [comment]
I was reading some Figma documentation today and really liked their note component:

![image](https://user-images.githubusercontent.com/8960591/74205292-9d9f7800-4c2b-11ea-91fe-da468abfd001.png)

https://help.figma.com/hc/en-us/articles/360039823654-Download-the-Figma-Desktop-App

**Comment by yaili** [comment]
Looks cool. 

They also seem to have different types of notes:
<img width="679" alt="Screenshot 2020-02-11 at 19 00 34" src="https://user-images.githubusercontent.com/223966/74269063-d1989d00-4d00-11ea-9993-a7cfaa72a3ce.png">
https://help.figma.com/hc/en-us/articles/360039829154-Receive-Comment-Notifications-in-Slack

<img width="682" alt="Screenshot 2020-02-11 at 19 01 01" src="https://user-images.githubusercontent.com/223966/74269099-dd845f00-4d00-11ea-9c07-37247d80acb9.png">

https://help.figma.com/hc/en-us/articles/360039829254-ProtoPie-and-Figma 


And guessing this is the default box style:
<img width="680" alt="Screenshot 2020-02-11 at 19 01 47" src="https://user-images.githubusercontent.com/223966/74269158-f9880080-4d00-11ea-9d9d-d6ced903f987.png">
https://help.figma.com/hc/en-us/articles/360039829154-Receive-Comment-Notifications-in-Slack

**Comment by emplums** [comment]
Yeah! This style might be too bold for GitHub but I do like that it really stands out on the page and feels kinda slick. I think we could use something outside of the design system though for these notes since they do have a pretty specific purpose that differs from how we use Alerts in .com

**Comment by emplums** [comment]
Latest design here: https://www.figma.com/file/qsKUZDH4xE8h6e7p7GBE8e/Doctocat-Extra-components?node-id=291%3A0

![image](https://user-images.githubusercontent.com/8960591/76349190-c7010180-62c6-11ea-90e6-b4f0c3a8f5e6.png)

**Comment by colebemis** [comment]
@yaili What different types of alerts do we want to support? It'd be helpful if we could list them all out and assign them colors.

**Comment by yaili** [comment]
@colebemis I think we'd have a warning/danger, alert, tip, and default (the blue one, Figma Docs calls it "note").

Would we want to align with names of our Primer components?

**Comment by colebemis** [comment]
Closed by #167
