### ISSUE TITLE
[Component] Multiple component variations

### ISSUE THREAD

**Issue by yaili** [primer/doctocat#111]
How can we show multiple component variations in a space-saving way?

Example: [Polaris dropdown](https://polaris.shopify.com/components/actions/button#navigation)

<img width="887" alt="Screenshot 2020-01-28 at 14 31 39" src="https://user-images.githubusercontent.com/223966/73272830-eb06f880-41da-11ea-8220-ed84fe86118b.png">

**Comment by colebemis** [comment]
@brianlovin shared a demo of a tool he built to visualize all the variants of component designs. It seemed relevant to this issue :) https://twitter.com/brian_lovin/status/1233290048709152773

**Comment by yaili** [comment]
Let's reopen when we come back to this.
