### ISSUE TITLE
LICENSE file?

### ISSUE THREAD

**Issue by jeffwilcox** [primer/doctocat#118]
Hi,
I was wondering how this project is licensed?

I'd love a `LICENSE` file in the root and also a `license` property in the `package.json`... happy to add these assets if there's a known license for Primer or Doctocat that the maintainers agree on.

(I'm looking to egregiously borrow some of the doctocat theme components in adapting my own Primer theme for an internal MSFT resource)

**Comment by colebemis** [comment]
Hi @jeffwilcox 👋 Thanks for opening this issue. We use the **MIT license** for our other open source projects. Let's do the same for Doctocat. 

> ... happy to add these assets if there's a known license for Primer or Doctocat that the maintainers agree on.

We'd love a PR adding the MIT license to the repo. Feel free to reach out if you have any questions about the contribution process 😊
