### ISSUE TITLE
New Table of Contents

### ISSUE THREAD

**Issue by emplums** [primer/doctocat#120]
@yaili and I have been working through some new iterations for components in our docs! One of the items that we'll need to build out is a new table of contents. Instead of having the table of contents take up a large portion of the main content area, we are moving the TOC to a sidebar.

### Requirements
- TOC is automatically generated from the headings on the page. You can access the table of contents via `pageContext`. I think this is something that MDX provides and we access via graphql in `gatsby-node.js`)
- Should be `position: sticky`

### Screenshot
![image](https://user-images.githubusercontent.com/8960591/75098244-b7648780-5568-11ea-987f-5e75ea846c06.png)

### Figma
[Figma file](https://www.figma.com/file/qsKUZDH4xE8h6e7p7GBE8e/Doctocat-Extra-components?node-id=291%3A0) See frame 16.

For now the first iteration, let's just focus on getting the table of contents into the sidenav, but in the future we'll also want to append a "references" section below the table of contents.

### Open Questions
- @yaili In the latest Figma frame, I see that there is a yellow bar beside one of the table of content items. Should this show up only when the URL matches that section (this would only happen when someone clicks on a link in the table of contents, clicks on a heading, or comes directly to a URL that references one of the headings in the page), or should that bar update as the user scrolls through the page?

**Comment by yaili** [comment]
I was thinking that bar updates as the user scrolls.

**Comment by yaili** [comment]
Related https://github.com/primer/doctocat/issues/53
