### ISSUE TITLE
Persistent navigation position

### ISSUE THREAD

**Issue by yaili** [primer/doctocat#122]
When we click on a page in the navigation, if the navigation is really long (lots of items, example: https://primer.style/css/), the navigation goes back to the top on page load.

Could we make it stay in place, somehow? Example: https://auth0-cosmos.now.sh/docs/#/

Could it be an option in Doctocat? Maybe not every instance would need this feature on.

_Update_

One more example:
https://www.gatsbyjs.org/docs/creating-prefixed-404-pages-for-different-languages/

**Comment by colebemis** [comment]
Gatsby documentation on scroll restoration: https://www.gatsbyjs.com/docs/scroll-restoration
