### ISSUE TITLE
Top nav breaking on primer.style/design

### ISSUE THREAD

**Issue by ashygee** [primer/doctocat#141]
The title and top nav drop to two lines. I suspect this is because "Interface guidelines" is lengthy.

<img width="1003" alt="Screenshot 2020-04-29 15 51 11" src="https://user-images.githubusercontent.com/10384315/80654736-d5031100-8a31-11ea-965e-ed4558885b3b.png">

cc @colebemis

**Comment by yaili** [comment]
The mobile navigation breakpoint needs to happen a bit sooner. @colebemis
