### ISSUE TITLE
‘Add a primer.style path alias’

### ISSUE THREAD

**Issue by hifocus** [primer/doctocat#143]
In Add a primer.style path alias and https://primer.style/doctocat/usage/deployment#4-update-nowjson-in-primerprimerstyle, I read this: after the configuration, I can open a pull request within the format; once approved, my own docs site can be access under https://primer.style/my-site

While I understand you just made this repository public, which is very kind for the benefic of the open source community, but should the statement above be true to everyone so that the public can let you host thier docs sites, or it's just a internal thing that it's just the documentation haven't been updated soon enough?

Many thanks for any potential answers :D

**Comment by emplums** [comment]
Hey @hifocus! This docs site is meant for GitHub design systems documentation only! Thanks for asking! :)
