### ISSUE TITLE
Shadowing the header.js requires to shadow most of /components/ to work

### ISSUE THREAD

**Issue by jpvalery** [primer/doctocat#152]
Hi there,

Thank you so much for making this available publicly. 

I'm building a gatsby site for our company's docs and I'm using doctocat. My only pet peeve is that shadowing header.js requires to shadow almost all of the files `/components` as well as `use-search.js` and I feel it's making the whole point of gatsby-themes useless in this case. 

Is there a better way to proceed to customize the header component? (basically removing the GitHub logo and Primer). 

Thanks in advance!

**Comment by colebemis** [comment]
Hi, @jpvalery 👋  We made Doctocat specifically for Primer documentation sites. So making the header easy to shadow wasn't a priority for us. If we decide to make Doctocat more general-purpose, we'll revisit this issue. Thanks!
