### ISSUE TITLE
Tooltip component preview not working in Safari 

### ISSUE THREAD

**Issue by auareyou** [primer/doctocat#156]
Looks like tooltips don't pop up when hovering over the trigger. Seems to only be an issue in Safari. Chrome is working fine. 
https://primer.style/css/components/tooltips

<img width="855" alt="Screen Shot 2020-07-21 at 19 03 54" src="https://user-images.githubusercontent.com/6951037/88084598-f2550080-cb84-11ea-9941-2eacd42732da.png">

similar issue here: https://github.com/primer/css/issues/1105

**Comment by yaili** [comment]
I couldn't replicate this bug, pls reopen if still valid. 🙏🏼
