### ISSUE TITLE
Keeping Everything Fresh 🌱

### ISSUE THREAD

**Issue by emplums** [primer/doctocat#157]
Doctocat is starting to get a fair amount of traction! 🎉 This is wonderful news, and leads me to think we need to start defining some processes for keeping everything up to date and if possible, automating this process.

## Goals
- primer/doctocat should always have the latest version of Primer React Components and Primer Octicons
- primer/dotocat-template should always be using the latest version of the doctocat theme
- All of our documentation sites should be using the latest version of the doctocat theme 

## Roadblocks
- Keeping all of these up to date is time consuming. Take for example shipping a new version of Primer Components. Afterwards, we'd need to update the version in primer/doctocat, which would mean we'd need to ship a new release. Then we'd need to update each of our doc sites (I believe we're up to 10+ doc sites at the moment), and the primer/doctocat-template repository with the new doctocat theme verison.

Because this is so tedious, we don't often do it 😬 Many of the docs sites are currently using old versions of doctocat, and the doctocat template is using a version of the doctocat theme that is 12 versions old 😬 

## Potential solutions
- Could we use a GitHub Action that automatically creates a new PR for all our docs sites when primer/doctocat ships a new version?
- Could dependabot do this for us?
- If there isn't an easy way to automate this, would it make sense to schedule a recurring time to do this manually once a month?

**Comment by emplums** [comment]
cc @BinaryMuse since you are 💯 at thinking of cool ways to automate things, do you have any ideas??

**Comment by BinaryMuse** [comment]
Currently we're pseudo-automating this with [multibump](https://github.com/BinaryMuse/multibump), but it's still under construction and probably not quite ready for general use (and the readme is wrong 🙈). Ideally something like Dependabot would just open PRs for us that we could simply merge into `main`.
