### ISSUE TITLE
Highlight the current section in the table of contents

### ISSUE THREAD

**Issue by colebemis** [primer/doctocat#169]
As you scroll down a documentation page, the current section should be highlighted in the sticky table of contents.

Here's @ashygee's design for the "highlight":

![image](https://user-images.githubusercontent.com/4608155/91345782-c4229c00-e794-11ea-8292-999ae46724f8.png)

### References
* https://docs.gitbook.com/organizations/organization-management#setup-single-sign-on-sso
* https://www.ifixit.com/Device/Mac

**Comment by SferaDev** [comment]
@colebemis Opened a pull request on this! 😄
