### ISSUE TITLE
"Primer React" not renamed across all sites

### ISSUE THREAD

**Issue by yaili** [primer/doctocat#180]
Hi! 👋🏼 

Some sub-sites still say Primer Components instead of Primer React:
https://primer.style/design/
https://primer.style/presentations/
https://primer.style/css/

cc @emplums

**Comment by colebemis** [comment]
I have PRs open to update all of those sites:
- https://github.com/primer/presentations/pull/60
- https://github.com/primer/design/pull/118
- https://github.com/primer/css/pull/1159

They're all failing tests for some reason and I haven't had a chance to look into why yet. But it's on my list to merge those this week.

**Comment by emplums** [comment]
@colebemis let me know if you need a hand with those failing tests!

**Comment by colebemis** [comment]
@emplums Thanks! I think @BinaryMuse is looking into them today.
