### ISSUE TITLE
Layout issue in LiveCode component

### ISSUE THREAD

**Issue by maiertech** [primer/doctocat#207]
I'm using the theme to document a component library. I came across a Layout issue in the `LiveCode` component. I will first show with screenshots from one specific page what the problem looks like and then follow-up with what I think is happening.

At v0.25.3 I get this (note the difference between the two examples is the alignment prop):

<img width="863" alt="Screen Shot 2020-11-27 at 10 23 34 PM" src="https://user-images.githubusercontent.com/1482402/100492953-021abd80-3100-11eb-87cc-4bd024e1ae74.png">

At v1.0.0 I get this (note that the second example is not aligned center any more):

<img width="878" alt="Screen Shot 2020-11-27 at 10 31 42 PM" src="https://user-images.githubusercontent.com/1482402/100492977-59b92900-3100-11eb-9552-0cbb5ba117c4.png">

Chrome devtools show that at v0.25.3 the `div` that wraps the rendered example stretches the available space:

<img width="1007" alt="Screen Shot 2020-11-27 at 10 35 31 PM" src="https://user-images.githubusercontent.com/1482402/100493035-08f60000-3101-11eb-8ef9-7dd59cb61180.png">

But at v1.0.0 this is not the case any longer. The wrapping `div` is only as big as its content, presumably because its parent is now rendered with `display: flex` and therefore, it turns into a flex item that ignores `display: block`. As a result, the example component cannot stretch and the `align` prop has no effect:

<img width="922" alt="Screen Shot 2020-11-27 at 10 37 40 PM" src="https://user-images.githubusercontent.com/1482402/100493079-84f04800-3101-11eb-980c-46bb4706c051.png">

When I compare v0.25.3 with v1.0.0, is see that in [`LiveCode` the `LivePreviewWrapper` is now wrapped with `Flex`](https://github.com/primer/doctocat/compare/v0.25.3...@primer/gatsby-theme-doctocat@1.0.0#diff-d6d121849600f8a5feae67c4d37859a2c938eedd44b0f52b0755626971fef794L53-R61) (click the link to see the comparison, I marked the lines in the comparison, but you need to scroll down to `live-code.js` to see it).

I am not sure what added value the newly introduced `Flex` element brings, but that's maybe because I have not dissected the overall layout enough. But I think that any rendered examples should be allowed to stretch the entire available width.

**Comment by colebemis** [comment]
👋 Thanks for opening this issue, @454de6e. I think using a div with a `width` of `100%` in your `LivePreviewWrapper` should fix the problem: 
![image](https://user-images.githubusercontent.com/4608155/100788863-886a2480-33ca-11eb-8c9d-e3963b5d1131.png)
 
Let me know if that works 😄

**Comment by 454de6e** [comment]
@colebemis that fixes it, obviously 😄. Would it not make more sense to fix this in the theme in one of the wrapping divs? I would expect my components to expand the entire width in the examples rather than rendering with their inherent width.
