### ISSUE TITLE
Stale instructions

### ISSUE THREAD

**Issue by mattalexander-pantheon** [primer/doctocat#245]
On this page:

You say this, near the bottom:

> ### 4. Update now.json in primer/primer.style
> 
> After everything is set up in your repository, open a pull request on the [primer/primer.style](https://github.com/primer/primer.style) repository to add your site to the `routes` list in [now.json](https://github.com/primer/primer.style/blob/master/now.json):
> 
> ```diff
> // now.json in primer/primer.style
> {
>   "routes": [
>     {"src": "/components(/.*)?", "dest": "https://primer-components.now.sh"},
>     {"src": "/css(/.*)?", "dest": "https://primer-css.now.sh"},
>     {"src": "/design(/.*)?", "dest": "https://primer-design.now.sh"},
>     {"src": "/blueprints(/.*)?", "dest": "https://primer-blueprints.now.sh"},
>     {"src": "/presentations(/.*)?", "dest": "https://primer-presentations.now.sh"},
> +   {"src": "/my-site(/.*)?", "dest": "https://my-site.now.sh"}
>   ]
> }
> ```
> 
> Once your pull request is approved and merged, you'll be able to access your site from `primer.style/my-site`. 🎉

But that `now.js` file doesn't exist.

**Comment by colebemis** [comment]
Good catch. Thank you!
