### ISSUE TITLE
Links in primer global nav

### ISSUE THREAD

**Issue by broccolini** [primer/doctocat#48]
To ensure people find all the things, I think we should cross-link to related documentation sites where needed. Some things aren't ready yet but I wanted to capture what I was thinking should go in each of the dropdowns.

### Design 🔽 

| Title                           | Link                                         | Status |
|---|---|---|
| Interface guidelines | https://primer.style/design   | ✅ |
| Octicons                   | https://octicons.github.com | ✅ |
| Prototyping              | https://primer.style/css/tools/prototyping | ✅ |
| Presentations           | https://primer.style/presentations | ✅ |
| Email                         | https://primer.style/email | Not shipped |
| Illustration                | https://primer.style/illustration | Not transferred |
| Brand                        | https://brand.github.com | ✅|
| Logos                        | https://github.com/logos | ✅|

**Questions:** 
- should we differentiate links that aren't in the primer.style domain? Perhaps with ➡️ icon or something?
- how should this be ordered? alphabetical or something else?
- do these feel like the right links in the right section?

### Development 🔽 

| Title                           | Link                                         | Status |
|---|---|---|
| Primer CSS               | https://primer.style/design   | ✅ |
| Primer Components | https://octicons.github.com | ✅ |
| Email build tool         | https://github.com/github/email-build-tool | ✅ |

(In future we might want to cross-link to other dev documentation like web systems but I think this is good for now.)

**Question:** Since the email build tool is only accessible to staff, should we add a 🔒icon or something on that and other private links?

### Content

| Title                           | Link                                         | Status |
|---|---|---|
| Content | https://primer.style/content   | Not transferred |

### About

In future I think we can flesh out more detail under "about", something like this:

- Who can use Primer? (Link to About page and explain usage)
- Team (link to About page team profiles section)
- Open-source (links to primer org)
- Contributing
  - Design and code contribution guidelines for all parts of our design system
  - Guidelines for how to build, customize, and maintain Primer documentation websites (perhaps this links to primer.style/doctocat ?)

### What's New

Once the updates to primer.style are completed (homepage and the news feed), I think we could make it easier to jump to releases etc.:

- Releases / changelog (should we have a global changelog?)
- Posts (articles, talks, podcasts, interviews)

---

Feedback welcome!

cc @primer/ds-core

**Comment by yaili** [comment]
Closing for now.
