### ISSUE TITLE
Add New Do/Don't Component 

### ISSUE THREAD

**Issue by emilybrick** [primer/doctocat#49]
Ref https://github.com/github/design-systems/issues/661

This would include deprecating the old styles.

**Comment by emilybrick** [comment]
Styling for this can be found: https://primer.style/design/ui-patterns/messaging

Considerations for the component:
- though the images should appear side-by-side on desktop, the user should have the *option* to let the images stack on desktop if necessary, for images that are landscape like this:
<img width="1009" alt="Screenshot 2019-08-16 14 52 59" src="https://user-images.githubusercontent.com/586552/63191078-aecd4a80-c035-11e9-8917-df6aaee3961b.png">

- regardless, it needs responsive styling so that it stacks on mobile

**Comment by colebemis** [comment]
Closed by #63
