### ISSUE TITLE
Add caption component

### ISSUE THREAD

**Issue by emilybrick** [primer/doctocat#51]
It would be useful to include a caption component. We use captions in the ["Do/Don't"](https://github.com/primer/doctocat/issues/49) component, but also underneath regular images.

Currently, it looks like this:
<img width="749" alt="Screenshot 2019-08-16 14 56 22" src="https://user-images.githubusercontent.com/586552/63191237-079ce300-c036-11e9-8c4d-e9525d4812ce.png">

Proposed:
<img width="740" alt="Screenshot 2019-08-16 14 56 49" src="https://user-images.githubusercontent.com/586552/63191264-14213b80-c036-11e9-93fc-768d9517ee26.png">

Styling to achieve ☝️: 
`<Text fontSize="0" color="gray.5">Fold/Unfold Icon used in Profiles context</Text>`

**Comment by colebemis** [comment]
Closed by #61
