### ISSUE TITLE
Documentation content vertical spacing

### ISSUE THREAD

**Issue by nsolerieu** [primer/doctocat#699]
The current documentation markdown page use very tight vertical spacing which leads to a very dense "wall of text" effect. I'd suggest to update our spacing classes to promote an easier reading experience.

---

Before: most of the spacing is handled by `margin-bottom` rules on paragraphs and headings and is set at 16px

![Image](https://github.com/primer/doctocat/assets/10632534/7dbac210-dca9-4b1b-8313-08b62fe9bfe0)

---

Suggestion: We could consider creating a stronger visual hierarchy by having larger spacing above the heading with a gradual scale. H2 would have a greater margin top of 64px than and H3 at 48px. Margin bottom should also follow this logic and to allow the text to pair withe the heading. The bulk of our documentation seems to use h2 and h3 extensively so addressing these 2 could alleviate a lot of the visual density.

Paragraphs could be bumped up to `margin-bottom:24px`

![Image](https://github.com/primer/doctocat/assets/10632534/c90fdeda-5a4f-4ac6-82a6-9723619ee42b)

---

Before/after

![Image](https://github.com/primer/doctocat/assets/10632534/fd5660b5-5c12-41ae-95ed-8b86fa9921b4)

**Comment by tallys** [comment]
Heads up @mperrotti - let's invite @nsolerieu to a Primer Patterns so we can get on the same page about the design for Primer.style.

**Comment by nsolerieu** [comment]
PRs are open:
- Paragraphs: https://github.com/primer/doctocat/pull/705
- Headings: https://github.com/primer/doctocat/pull/706
