### ISSUE TITLE
Add "Skip to main content" link

### ISSUE THREAD

**Issue by dmarcey** [primer/doctocat#82]
Should we add a "Skip to main content" link to Doctocat that allows a keyboard-only user the ability to navigate directly to the page's content and bypass all of the navigation tab stops?

https://webaim.org/techniques/skipnav/

I was thinking of something similar to docs for gatsbyjs: https://www.gatsbyjs.org/docs/mdx/writing-pages/ (load the page and hit tab to see the example).

Something like the following as a starting point:

![Screenshot showing a Skip to main content link on the Doctocat page](https://user-images.githubusercontent.com/5487287/64556063-aef6f800-d30c-11e9-9526-b60268cc1d83.png)

Let me know if we would want something like this to be added to the doctocat theme and I can at least work on wiring up the functionality and then solicit feedback on design of the link.

**Comment by colebemis** [comment]
This is a great idea! I'd love to see this added to Doctocat.
